environment:
  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.0"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"

  # Setting up enviroment
  - "pip install pipenv"
  - "pipenv install --dev --ignore-pipfile"

build: off

test_script:
  - "pipenv run py.test --cov=mimesis"
  - "pipenv run mypy mimesis tests"
  - "pipenv run pyroma -d ."
